query InvoicesIdRequestsId($id: Int!) {
  getRequest(id: $id) {
    id
    requester {
      id
      givenName
      familyName
    }
    comments {
      id
      content
      user {
        id
        givenName
        familyName
      }
    }
  }
}

mutation CreateJudgement($newJudgement: NewJudgementInput!) {
  addJudgement(newJudgement: $newJudgement) {
    id
    type
    user {
      id
    }
    request {
      id
    }
  }
}
