version: "3.7"
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  back:
    build:
      context: ./back
    working_dir: /back
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./back:/back
    depends_on:
      - db

  db:
    platform: "linux/amd64"
    image:
      postgres:14.1
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_sample
      POSTGRES_ROOT_PASSWORD: dev_sample
      POSTGRES_INITDB_ARGS: "--encoding=utf8 --locale=en_US.utf8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/postgresql/
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
      - "33060:33060"

  front:
    build:
      context: ./front
      target: development
    volumes:
      - ./front:/front
      - npm-cache:/front/node_modules
    ports:
      - "80:3000"
    working_dir: /front
    command: sh -c "npm install && npm start"

volumes:
  npm-cache:
