query InvoiceLog($id: String!) {
  getInvoiceLog(id: $id) {
    id
    body {
      label
      value
    }
    invoice_format_log {
      id
      body {
        order
        label
        own
      }
    }
  }
}
