query IssueId($id: String!) {
  getInvoiceLog(id: "fd4aebf6-559f-4a21-b655-b5483a9a0fab") {
    id
    body {
      elementId
      value
    }
    detail {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
        order
        own
        valueType
      }
      detailElements {
        id
        order
        label
        valueType
        own
      }
    }
  }
}

mutation IssueIdUpdateInvoiceLog($input: UpdateInvoiceLogInput!) {
  updateInvoiceLog(input: $input) {
    id
    createdAt
    body {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        company {
          name
        }
      }
      elements {
        id
        order
        label
        valueType
        own
      }
    }
  }
}
