query IssueId($id: String!) {
  invoice(id: $id) {
    id
    body {
      elementId
      value
    }
    detail {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
        order
        own
        valueType
      }
      detailElements {
        id
        order
        label
        valueType
        own
      }
    }
  }
}

mutation IssueIdUpdateInvoice($input: UpdateInvoiceInput!) {
  updateInvoice(input: $input) {
    id
    createdAt
    body {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        company {
          name
        }
      }
      elements {
        id
        order
        label
        valueType
        own
      }
    }
  }
}

mutation IssueIdUploadInvoiceFile($invoiceId: String!, $file: Upload!) {
  uploadInvoiceFile(invoiceId: $invoiceId, file: $file) {
    pathName
    invoiceId
  }
}
