query Issues {
  invoice_logs {
    id
    body {
      elementId
      value
    }
    invoice_format_log {
      id
      elements {
        id
        order
        label
        own
      }
    }
  }
}
