query GetInvoice($id: String!) {
  getInvoice(id: $id) {
    id
    billingDate
    dueDateForPayment
    paymentAmount
    status
    createdBy {
      id
      familyName
      givenName
    }
    construction {
      id
      name
    }
    company {
      id
      name
    }
  }

  getInvoiceLog(id: "fd4aebf6-559f-4a21-b655-b5483a9a0fab") {
    body {
      elementId
      value
    }
    detail {
      elementId
      value
    }
    invoiceFormatLog {
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
      }
      detailElements {
        id
        order
        label
      }
    }
  }
}
