query InvoicePDF($invoiceLogId: String!) {
  getInvoiceLog(id: $invoiceLogId) {
    body {
      elementId
      value
    }
    invoiceFormatLog {
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
      }
    }
  }
}
