query InvoiceId($id: String!) {
  getInvoice(id: $id) {
    id
    status
    createdBy {
      id
      familyName
      givenName
    }
    construction {
      id
      name
    }
    company {
      id
      name
    }
    body {
      elementId
      value
    }
    detail {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
        order
        own
        valueType
      }
      detailElements {
        id
        order
        label
        valueType
        own
      }
    }
    requestPairStatus {
      receiverRequest {
        id
      }
      requesterRequest {
        id
      }
      invoiceStatusFromUserView
    }
  }

  users {
    id
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    email
    isAdmin
    employeeCode
  }
}

mutation InvoiceIdReceive($input: ReceiveInvoiceInput!) {
  receiveInvoice(input: $input) {
    id
  }
}

mutation InvoiceIdApprove($input: ApproveRequestInput!) {
  approveInvoice(input: $input) {
    id
  }
}

mutation InvoiceIdDecline($input: DeclineRequestInput!) {
  declineInvoice(input: $input)
}

mutation InvoiceIdReapply($input: ReapplyRequestInput!) {
  reapplyInvoice(input: $input)
}
