query IssueIdView($id: String!) {
  getInvoice(id: $id) {
    id
    body {
      elementId
      value
    }
    detail {
      elementId
      value
    }
    invoiceFormatLog {
      id
      invoiceFormat {
        name
        company {
          name
        }
      }
      elements {
        id
        label
        order
        own
        valueType
      }
      detailElements {
        id
        order
        label
        valueType
        own
      }
    }
  }
  currentUser {
    id
    email
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    employeeCode
    createdAt
    isAdmin
  }
}

mutation IssueIdViewSendInvoice($input: SendInvoiceInput!) {
  sendInvoice(input: $input) {
    id
    createdById
    createdAt
    updatedAt
    updatedDataAt
  }
}
