query UnconfirmedUsers {
  adminUnconfirmedUsers {
    email
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    employeeCode
    createdAt
    isAdmin
    company {
      id
      name
    }
  }
  adminCompanies {
    id
    name
  }
}

mutation CreateUnconfirmedUser($newUnconfirmedUser: AdminNewUnconfirmedUserInput!) {
  adminAddUnconfirmedUser(newUnconfirmedUser: $newUnconfirmedUser) {
    email
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    createdAt
    company {
      id
      name
    }
  }
}
