query GetRequest($id: Int!) {
  getRequest(id: $id) {
    id
    requester {
      id
      given_name
      family_name
    }
    comments {
      id
      content
      user {
        id
        given_name
        family_name
      }
    }
  }
}
