query Approvals {
  users {
    id
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    email
    isAdmin
    employeeCode
  }
  invoices {
    id
    createdAt
    createdById
    companyId
    status
  }
}
