query InvoiceFormatLogs {
  invoiceFormatLogs {
    id
    invoiceFormat {
      id
      name
      company {
        id
        name
      }
    }
  }
}

mutation CreateInvoiceLog($input: NewInvoiceLogInput!) {
  addInvoiceLog(newInvoiceLog: $input) {
    id
  }
}
