query Formats {
  invoiceFormatLogs {
    id
    invoiceFormat {
      id
      name
      company {
        id
        name
      }
    }
  }
}

mutation FormatsCreateInvoice($input: NewInvoiceInput!) {
  addInvoice(newInvoice: $input) {
    id
  }
}
