query Receipts {
  invoicesByStatus(status: awaitingReceipt) {
    id
    billingDate
    dueDateForPayment
    paymentAmount
    status
    construction {
      id
      name
    }
    companyId
  }
}
