query SignUpCheckEmail($email: String!) {
  unconfirmedUser(email: $email) {
    email
    familyName
    givenName
    familyNameFurigana
    givenNameFurigana
    isAdmin
    employeeCode
    createdAt
    company {
      id
      name
    }
  }
}

mutation SignUp($newUser: NewUserInput!) {
  addUser(newUser: $newUser) {
    id
    email
  }
}
