query RequestSend {
  users {
    id
    family_name
    given_name
    family_name_furigana
    given_name_furigana
    email
    is_admin
    employee_code
  }
}

mutation CreateRequest($newRequest: NewRequestInput!) {
  addRequest(newRequest: $newRequest) {
    id
    requester {
      id
      given_name
      family_name
      email
      employee_code
      company {
        id
        name
      }
    }
  }
}
