apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: 237064188084.dkr.ecr.ap-northeast-1.amazonaws.com/invoice-backend-dev:SHORT_SHA
          command: ["npm", "run", "migration:run", "--", "&&", "npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: back-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.4"
