name: admin lint
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./admin
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run lint
      - run: npm run fmt
