name: Deploy Backend
on:
  push:
    branches:
      - main
      - 50-feat-deployment_init

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
  
    - name: Build a docker image
      run: |
        docker build \
        -t 237064188084.dkr.ecr.ap-northeast-1.amazonaws.com/invoice-backend-dev:${{ env.SHA }} \
        -f _deploy/docker/back/Dockerfile ./back

    - name: Login
      run: aws ecr get-login-password | docker login --username AWS --password-stdin 237064188084.dkr.ecr.ap-northeast-1.amazonaws.com/invoice-backend-dev

    - name: Push docker image
      run: docker push 237064188084.dkr.ecr.ap-northeast-1.amazonaws.com/invoice-backend-dev:${{ env.SHA }}

    # SHORT_SHA を置換
    - run: sed -i -e 's/SHORT_SHA/${{ env.SHA }}/g' _deploy/k8s/back/deployment.yml
    - run: sed -i -e 's/SHORT_SHA/${{ env.SHA }}/g' _deploy/k8s/back/service.yml


    - name: Install kubectl (Not related to Azure)
      uses: azure/setup-kubectl@v1

    - name: Run kubectl
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV }}
      run: |
        echo "$KUBE_CONFIG_DATA" > /tmp/kube_config
          export KUBECONFIG=/tmp/kube_config
          kubectl apply -f _deploy/k8s/back/deployment.yml
          kubectl apply -f _deploy/k8s/back/service.yml
