name: Deploy Frontend
on:
  push:
    branches:
      - main
      - 50-feat-deployment_init

env:
  REACT_APP_BACKEND_HOST: ${{ secrets.API_HOST }}

defaults:
  run:
    working-directory: ./front

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME_DEV }} --delete
