name: Preview Deployment

on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/create-namespace@latest
      with:
        namespace: invoice-${{ github.event.number }}-bababax11
   
    - name: Deploy application
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
        bababax11: invoice-${{ github.event.number }}-bababax11

    - name: add comment to PR
      uses: okteto/notify-pr@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: "Preview environment available at https://web-invoice-${{ github.event.number }}-bababax11.cloud.okteto.net"
