name: tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker/tests/docker-compose.yml up --build --abort-on-container-exit
